const profileActionTypes = {
  FETCH_PROFILEIMAGE_PENDING: "FETCH_PROFILEIMAGE_PENDING",
  FETCH_PROFILEIMAGE_SUCCESS: "FETCH_PROFILEIMAGE_SUCCESS",
  FETCH_PROFILEIMAGE_FAILED: "FETCH_PROFILEIMAGE_FAILED",
  SEND_PROFILEIMAGE_PENDING: "SEND_PROFILEIMAGE_PENDING",
  FETCH_PROFILEINFO_PENDING: "FETCH_PROFILEINFO_PENDING",
  FETCH_PROFILEINFO_SUCCESS: "FETCH_PROFILEINFO_SUCCESS",
  NULLIFY_PROFILEIMAGE: "NULLIFY_PROFILEIMAGE",
  CHANGE_STATUS: "CHANGE_STATUS",
};

export default profileActionTypes;
