const shopActionTypes = {
  FETCH_ITEMS_PENDING: "FETCH_ITEMS_PENDING",
  FETCH_ITEMS_SUCCESS: "FETCH_ITEMS_SUCCESS",
  FETCH_CATEGORY_PENDING: "FETCH_CATEGORY_PENDING",
  FETCH_CATEGORY_SUCCESS: "FETCH_CATEGORY_SUCCESS",
  FETCH_ITEMS_FAILED: "FETCH_ITEMS_FAILED",
  FETCH_PRODUCT_PENDING: "FETCH_PRODUCT_PENDING",
  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  FETCH_FILTEREDITEMS_PENDING: "FETCH_FILTEREDITEMS_PENDING",
  FETCH_SELLINGITEMS_PENDING: "FETCH_SELLINGITEMS_PENDING",
  FETCH_SELLINGITEMS_SUCCESS: "FETCH_SELLINGITEMS_SUCCESS",
  FETCH_SELLINGITEMS_FAILED: "FETCH_SELLINGITEMS_FAILED",
};
export default shopActionTypes;
