
 const cartActionTypes = {
    TOGGLE_CART_HIDDEN : 'TOGGLE_CART_HIDDEN',
    ADD_ITEM : 'ADD_ITEM',
    MINUS_ITEM: 'MINUS_ITEM',
    CLEAR_ITEM_FROM_CART : 'CLEAR_ITEM_FROM_CART',
    CLEAR_ITEM_ALL_FROM_CART : 'CLEAR_ITEM_ALL_FROM_CART',
    VERIFY_PURCHASE: 'VERIFY_PURCHASE'

}
 export default cartActionTypes;
