const modalActionTypes = {
  TOGGLE_MODAL: "TOGGLE_MODAL",
  OPEN_MODAL: "OPEN_MODAL",
  TOGGLE_CHAT_MODAL: "TOGGLE_CHAT_MODAL",
  OPEN_CHAT_MODAL: "OPEN_CHAT_MODAL",
  TOGGLE_MESSAGE_BOX: "TOGGLE_MESSAGE_BOX",
  OPEN_MESSAGE_BOX: "OPEN_MESSAGE_BOX",
  OPEN_VIDEO_BOX: "OPEN_VIDEO_BOX",
  TOGGLE_VIDEO_BOX: "TOGGLE_VIDEO_BOX",
  TOGGLE_SUCCESS_BOX: "TOGGLE_SUCCESS_BOX",
};

export default modalActionTypes;
