const userActionTypes = {
    // SET_CURRENT_USER: 'SET_CURRENT_USER',
    GOOGLE_SIGNIN_PENDING: 'GOOGLE_SIGNIN_PENDING',
    SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
    SIGNIN_FAILED: 'SIGNIN_FAILED',
    EMAIL_SIGNIN_PENDING: 'EMAIL_SIGNIN_PENDING',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGNOUT_PENDING: 'SIGNOUT_PENDING',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNOUT_FAILED: 'SIGNOUT_FAILED',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    CHANGE_STATUS: 'CHANGE_STATUS'


    
  

}

export default userActionTypes;