const groupchatActionTypes = {
    CREATE_GROUP_PENDING: "CREATE_GROUP_PENDING",
    CREATE_GROUP_SUCCESS: "CREATE_GROUP_SUCCESS",
    CREATE_GROUP_FAILED: "CREATE_GROUP_FAILED",
    GET_GROUPS_PENDING: "GET_GROUPS_PENDING",
    GET_GROUPS_SUCCESS: "GET_GROUPS_SUCCESS",
    GET_GROUPS_FAILED: "GET_GROUPS_FAILED",
    SEND_MESSAGE_PENDING: "SEND_MESSAGE_PENDING",
    SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
    SEND_MESSAGE_FAILED: "SEND_MESSAGE_FAILED",
    FETCH_MESSAGE_PENDING: "FETCH_MESSAGE_PENDING",
    FETCH_MESSAGE_SUCCESS: "FETCH_MESSAGE_SUCCESS",
    FETCH_MESSAGE_FAILED: "FETCH_MESSAGE_FAILED",
    INCREMENT_LIKES_PENDING: "INCREMENT_LIKES_PENDING",
    INCREMENT_LIKES_SUCCESS: "INCREMENT_LIKES_SUCCESS",
    INCREMENT_LIKES_FAILED: "INCREMENT_LIKES_FAILED",
    FILTER_MESSAGES: "FILTER_MESSAGES",
    
  };
  
  export default groupchatActionTypes;
  