const groupchatActionTypes = {
  CREATE_GROUP_PENDING: "CREATE_GROUP_PENDING",
  CREATE_GROUP_SUCCESS: "CREATE_GROUP_SUCCESS",
  CREATE_GROUP_FAILED: "CREATE_GROUP_FAILED",
  GET_GROUPS_PENDING: "GET_GROUPS_PENDING",
  GET_GROUPS_SUCCESS: "GET_GROUPS_SUCCESS",
  GET_GROUPS_FAILED: "GET_GROUPS_FAILED",
  SEND_GMESSAGE_PENDING: "SEND_GMESSAGE_PENDING",
  SEND_GMESSAGE_SUCCESS: "SEND_GMESSAGE_SUCCESS",
  SEND_GMESSAGE_FAILED: "SEND_GMESSAGE_FAILED",
  FETCH_GMESSAGE_PENDING: "FETCH_GMESSAGE_PENDING",
  FETCH_GMESSAGE_SUCCESS: "FETCH_GMESSAGE_SUCCESS",
  FETCH_GMESSAGE_FAILED: "FETCH_GMESSAGE_FAILED",
  INCREMENT_LIKES_PENDING: "INCREMENT_LIKES_PENDING",
  INCREMENT_LIKES_SUCCESS: "INCREMENT_LIKES_SUCCESS",
  INCREMENT_LIKES_FAILED: "INCREMENT_LIKES_FAILED",
  FILTER_MESSAGES: "FILTER_MESSAGES",
  SET_CURRENT_GROUP: "SET_CURRENT_GROUP",
  FETCH_GROUPDATA_PENDING: "FETCH_GROUPDATA_PENDING",
  FETCH_GROUPDATA_SUCCESS: "FETCH_GROUPDATA_SUCCESS",
  FETCH_GROUPDATA_FAILED: "FETCH_GROUPDATA_FAILED"
};

export default groupchatActionTypes;
